Feat: add docker-compose with prod requisites
CanalTP/forseti pull request #22
Opened 2021-03-26 09:02 UTC by Aletor93

Here, I'll add : 
- Traefik config
- Logging config
- Volume rework (still needs to be improved)

The actual `docker-compose.yaml` should be renamed `docker-compose.local.yaml` (or `docker-compose.dev.yaml` or whatever..).
And then this docker-compose file should be renamed `docker-compose.yaml` instead of `docker-compose.prod.yaml`.

2021-03-26 09:20 UTC, azime commented on docker-compose.prod.yaml
>      image: navitia/forseti:master
```suggestion
    image: navitia/forseti:latest OR  image: navitia/forseti:release
```

2021-03-26 09:34 UTC, azime approved these changes

2021-03-26 11:04 UTC, kadhikari approved these changes

2021-03-26 11:16 UTC, kadhikari commented on docker-compose.yaml
>        - FORSETI_ROUTESCHEDULE_REFRESH=300s
```suggestion
      - FORSETI_ROUTESCHEDULE_REFRESH=86400s
```

2021-03-26 11:17 UTC, kadhikari commented on docker-compose.local.yaml
> +      - FORSETI_ROUTESCHEDULE_REFRESH=300s
```suggestion
      - FORSETI_ROUTESCHEDULE_REFRESH=86400s
```

2021-03-26 11:19 UTC, kadhikari requested changes
We don't want to reload routeschedule every 5 minutes (300s), every hour will be enough

2021-03-26 11:21 UTC, kadhikari approved these changes

2021-03-26 11:28 UTC, Aletor93 commented
I'm not able to reach `/status` page provided with the image through the loadbalancer (Traefik).
I made some researches but didn't found anything yet. 

Forseti logs are available [here](http://ctp-int-logs.canaltp.prod/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15m,to:now))&_a=(columns:!(_source),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'673058a0-7806-11ea-b6df-9b3c3277ec8d',key:'@log_name',negate:!f,params:(query:forseti.departure),type:phrase),query:(match_phrase:('@log_name':forseti.departure)))),index:'673058a0-7806-11ea-b6df-9b3c3277ec8d',interval:auto,query:(language:kuery,query:forseti),sort:!())) for the Internal deployment.

2021-03-26 21:51 UTC, benoit-bst approved these changes

2021-03-31 09:12 UTC, kadhikari approved these changes

2021-04-06 12:33 UTC, Aletor93 commented
Hello, could we merge this branch please ? :) I'll update to master branch in my code.

2021-04-06 13:03 UTC, merged