Reshape vehicle occupancies
CanalTP/forseti pull request #27
Opened 2021-04-12 13:35 UTC by julyto

In the same way of an other ap, I isolated the vehicle occupancies code.

```
forseti
|
|---cmd
|     |---main.go
|---internal
|     |---vehiculeoccupancies
|     |    |---context.go
|     |    |---api.go
|     |    |---vehiculeoccupancies.go
|     |    |---vehiculeoccupancies_test.go
|     |    |---prometheus.go
|     | ...
|     | ...
|---Dockerfile
|---Makefile
|...
```

I also moved api.go in an API module and the manager of all the api's joined them in Internal module.

2021-04-12 18:43 UTC, benoit-bst approved these changes
This was a huge work for a first PR :clap: 
I think it is a good idea to reshape like that, for more readability and avoid the monolithic effect 

You dove into the code like a jedi !
![](https://media.giphy.com/media/zQhFEBrX6plKg/giphy.gif)

_Just a question_:

Have you run the magical line to start all services with real data ?

like that `./forseti --departures-uri file:///path/to/extract_edylic.txt --departures-refresh=1s --parkings-uri file:///forseti/fixtures/parkings.txt --parkings-refresh=30s --equipments-uri file:///forseti/fixtures/NET_ACCESS.XML --equipments-refresh=60s --occupancy-files-uri file:////NAVP-1750_vehicle_occupancies/data --occupancy-refresh=300s --occupancy-navitia-uri https://api.navitia.io/v1/coverage/fr-idf --occupancy-navitia-token token --occupancy-service-uri https://geteventsbyclientapi-rec-func-apim.azure-api.net --occupancy-service-token token --occupancy-service-refresh-active true --free-floatings-uri "https://flow-api.fluctuo.com" --free-floatings-token token --free-floatings-refresh=100s --free-floatings-refresh-active true`

2021-04-12 18:43 UTC, benoit-bst commented on api/api.go
> +			loadVehicleOccupanciesData = manager.GetVehiculeOccupanciesContext().LoadOccupancyData()
@kadhikari We need your expertise here :mag:

2021-04-12 18:43 UTC, benoit-bst commented on api/api_test.go
> +package api
Great idea to change the package name for that !
it's more precise

2021-04-12 18:43 UTC, benoit-bst commented on internal/manager/manager.go
> +package manager
:+1:

2021-04-13 06:58 UTC, benoit-bst commented
:bulb: On this PR or inside an other:

Can you create a readme like https://github.com/CanalTP/forseti/blob/master/internal/equipments/readme.md inside the folder to explain the services/Api ?

With a link into the main doc :

2021-04-13 07:09 UTC, julyto commented
> This was a huge work for a first PR 
> I think it is a good idea to reshape like that, for more readability and avoid the monolithic effect
> 
> You dove into the code like a jedi !
> ![](https://camo.githubusercontent.com/2804cccc913a0d7e7e19454be77a34437bb8a4039ce5cce80a79c672f8d57e0d/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f7a5168464542725836706c4b672f67697068792e676966)
> 
> _Just a question_:
> 
> Have you run the magical line to start all services with real data ?
> 
> like that `./forseti --departures-uri file:///path/to/extract_edylic.txt --departures-refresh=1s --parkings-uri file:///forseti/fixtures/parkings.txt --parkings-refresh=30s --equipments-uri file:///forseti/fixtures/NET_ACCESS.XML --equipments-refresh=60s --occupancy-files-uri file:////NAVP-1750_vehicle_occupancies/data --occupancy-refresh=300s --occupancy-navitia-uri https://api.navitia.io/v1/coverage/fr-idf --occupancy-navitia-token token --occupancy-service-uri https://geteventsbyclientapi-rec-func-apim.azure-api.net --occupancy-service-token token --occupancy-service-refresh-active true --free-floatings-uri "https://flow-api.fluctuo.com" --free-floatings-token token --free-floatings-refresh=100s --free-floatings-refresh-active true`

2021-04-13 07:17 UTC, julyto commented
Yes @benoit-bst I used the magical line to run all services with real life !
I will add a readme in api package and put the link into the main doc.

2021-04-13 11:27 UTC, benoit-bst approved these changes

2021-04-13 15:16 UTC, kadhikari requested changes
Can't we move code for data.go into context.go for each api?

Great work :+1:

2021-04-13 18:13 UTC, benoit-bst commented
@kadhikari, I think the data inside data.go is shared between several API. This is reason why I created this file. 
To check after that work

2021-04-14 07:16 UTC, kadhikari approved these changes

2021-04-14 11:57 UTC, merged