[Doc] Add departures doc
CanalTP/forseti pull request #30
Opened 2021-04-15 13:21 UTC by benoit-bst

2021-04-15 14:06 UTC, kadhikari requested changes

2021-04-15 14:06 UTC, kadhikari commented on internal/departures/readme.md
> +The realtime information is readed within an **.txt** like a **Csv** Style (**;** delimiter).
```suggestion
The realtime information is read within an **.txt** like a **Csv** Style (**;** delimiter).
```

2021-04-16 06:37 UTC, kadhikari approved these changes

2021-04-16 07:00 UTC, julyto approved these changes

2021-04-16 08:47 UTC, merged