Add vehicle locations to main
CanalTP/forseti pull request #54
Opened 2021-06-14 14:54 UTC by julyto

2021-06-17 11:22 UTC, benoit-bst approved these changes

2021-06-17 11:22 UTC, benoit-bst commented on internal/vehiclelocations/vehiclelocations.go
> +	//logrus.Debug("*** Vehicle Location updated: ", vehicleGtfsRt.Trip)
useless ?

2021-06-17 12:35 UTC, kadhikari requested changes

2021-06-17 12:35 UTC, kadhikari commented on cmd/forseti/main.go
> +	pflag.String("locations-files-uri", "", "format: [scheme:][//[userinfo@]host][/]path")
What we use it for ?

2021-06-18 09:22 UTC, julyto commented on internal/vehiclelocations/vehiclelocations.go
> +	//logrus.Debug("*** Vehicle Location updated: ", vehicleGtfsRt.Trip)
corrected

2021-06-18 09:22 UTC, julyto commented on cmd/forseti/main.go
> +func VehiculeLocations(manager *manager.DataManager, config *Config, router *gin.Engine, location *time.Location) {
corrected

2021-06-18 09:23 UTC, julyto commented on cmd/forseti/main.go
> +	var vehiculeLocationsContext vehiclelocations.IConnectors
corrected and verify everywhere

2021-06-18 09:23 UTC, julyto commented on internal/vehiclelocations/vehiclelocations.go
> +	//logrus.Debug("*** Vehicle Location updated: ", vehicleGtfsRt.Trip)
corrected

2021-06-18 09:23 UTC, julyto commented on cmd/forseti/main.go
> +	pflag.String("locations-files-uri", "", "format: [scheme:][//[userinfo@]host][/]path")
I keep this parameter as in Vehicle_Occupancy, but we usen't that at this time.

2021-06-22 06:59 UTC, kadhikari approved these changes

2021-06-22 07:08 UTC, merged