Add api vehicle_occupancies
CanalTP/forseti pull request #6
Opened 2021-02-19 08:26 UTC by kadhikari

* Work in progress.
* Tests to be added
* concerned ticket: https://jira.kisio.org/browse/NAVP-1750

2021-02-25 14:50 UTC, pbench reviewed
A few comments before finishing the review

2021-02-25 14:50 UTC, pbench commented on api.go
> +	// We accept two date formats in the parameter
Why accept two formats ? Is one not enough ?

2021-02-25 14:50 UTC, pbench commented on cmd/forseti/main.go
> +	location, _ := time.LoadLocation("Europe/Paris")
Maybe set the timezone as an (optional) command line/config argument rather than hardcode it

2021-02-25 17:08 UTC, kadhikari commented on api.go
> +	// We accept two date formats in the parameter
As two formats are standard, i was not able to fix which one to be used in our case.

2021-02-25 17:10 UTC, kadhikari commented on cmd/forseti/main.go
> +	location, _ := time.LoadLocation("Europe/Paris")
Do you mean optional -> with default value =  'Europe/Paris' ?

2021-02-25 17:26 UTC, pbench commented on cmd/forseti/main.go
> +	location, _ := time.LoadLocation("Europe/Paris")
yep, that's what I meant

2021-03-01 09:14 UTC, pbench commented on type.go
> +	Sens		int
```suggestion
	Direction	int  
```
and add a comment to state what `Direction` represents ?

2021-03-01 09:15 UTC, pbench commented on type.go
> +	sens, err := strconv.Atoi(record[3])
Can "sens" be any integer ?

2021-03-01 09:17 UTC, pbench commented on type.go
> +	Dow int
```suggestion
	DayOfweek int
```

2021-03-01 09:18 UTC, pbench commented on type.go
> +	FirstDate time.Time
there is no time.Date ?

2021-03-01 09:19 UTC, pbench commented on type.go
> +	Sens		int
```suggestion
	Direction		int
```

2021-03-01 09:20 UTC, pbench commented on type.go
> +	Charge    	int
```suggestion
	Load    	int
```
or
```suggestion
	Occupancy    	int
```

2021-03-01 09:25 UTC, pbench commented on type.go
> +}
Not very important, but `type.go` is becoming kind of big. 
Could this file be split into multiple files ? For example one for structs related to free_floating, another one for vehicle_occupancies, etc... ?

2021-03-01 09:26 UTC, pbench commented on utils.go
> +	return time.AddDate(date.Year(), int(date.Month())-1, date.Day()-1)
why do you need "-1" on month and day ?

2021-03-01 09:28 UTC, pbench requested changes
some cosmetic changes only,
huge work :+1:

2021-03-02 08:33 UTC, kadhikari commented on type.go
> +	sens, err := strconv.Atoi(record[3])
No it's either 0 or 1

2021-03-02 09:09 UTC, pbench commented on type.go
> +	sens, err := strconv.Atoi(record[3])
Maybe use a boolean instead of an integer then ? 
Or at least throw an error when the input is not 0 or 1

2021-03-02 10:29 UTC, kadhikari commented on type.go
> +}
As discussed i prefer to do it in another PR

2021-03-03 11:01 UTC, pbench commented on type.go
> +	for _, rs := range (*d.routeSchedules) {
If I understand correctly : this looks for a `rs` whose `rs.DateTime` is within two minutes of `dataTime`, and returns "" if no such vehicle_journey is found.

I think the "two minutes" is a bit arbitrary and may be too small or too big depending on the data.

I suggest replacing this by returning the `rs` such that `abs(rs.DateTime - dataTime)` is minimal.
Something like : 
```suggestion
min_distance = +inf
result = nil   
for _, rs := range (*d.routeSchedules) {
  if rs.Departure == true &&
  predict.LineCode == rs.LineCode &&
  predict.Sens == rs.Sens &&
  abs(rs.DateTime - dataTime) < min_distance
  {
      min_distance = abs(rs.DateTime - dataTime) 
      result = rs.VehicleJourneyId
  }
}
return result
```

2021-03-04 09:27 UTC, pbench approved these changes

2021-03-04 10:59 UTC, merged