Fix vj vehicle occupancy
CanalTP/forseti pull request #61
Opened 2021-09-10 13:45 UTC by julyto

2021-09-10 14:00 UTC, azime approved these changes

2021-09-13 07:44 UTC, kadhikari requested changes
Can you add or modify a test using sourcecode?
1. Test on addVJ
2. Test on Update with source

2021-09-13 07:44 UTC, kadhikari commented on internal/vehicleoccupancies/contextGtfsRt.go
> +			//si le vo n'existe pas
Comments should be in English non?

2021-09-13 13:06 UTC, julyto commented on internal/vehicleoccupancies/contextGtfsRt.go
> +			//si le vo n'existe pas
Test added and comments modified

2021-09-14 06:29 UTC, kadhikari approved these changes

2021-09-14 07:25 UTC, merged