Pagination forseti
CanalTP/forseti pull request #63
Opened 2021-09-15 08:18 UTC by julyto

Added possibility to get paginate for all connector.
Added paginate for freefloatings

2021-09-15 14:41 UTC, kadhikari requested changes

2021-09-15 14:41 UTC, kadhikari commented on internal/freefloatings/free_floatings_test.go
> +	assert.Equal(3, response.Paginate.Total_result)
Can you also verify the only free_floating returned by the query here ?

Another test with &distance=100&start_page=1&count=1. Normally there should be an empty free_floating along with a pagination having all 0 s.

2021-09-15 14:41 UTC, kadhikari commented on internal/freefloatings/free_floatings_test.go
> +	assert.Equal(3, response.Paginate.Total_result)
Can you verify at least one attribute of two elements returned by the query ?

2021-09-15 14:41 UTC, kadhikari commented on internal/freefloatings/context.go
> +			resp = nil
We never returned nil before. we initialized to 0 ->  resp := make([]FreeFloating, 0).
Have you tested what the web service response will be if resp = nil here?

2021-09-16 07:27 UTC, julyto commented on internal/freefloatings/api.go
>  	p.Count = utils.StringToInt(countStr, 10)
OK

2021-09-16 09:03 UTC, julyto commented on internal/freefloatings/free_floatings_test.go
> +	assert.Equal(3, response.Paginate.Total_result)
OK

2021-09-16 09:04 UTC, julyto commented on internal/freefloatings/free_floatings_test.go
> +	assert.Equal(3, response.Paginate.Total_result)
ok

2021-09-16 09:23 UTC, julyto commented on internal/freefloatings/context.go
> +			resp = nil
OK

2021-09-16 09:31 UTC, kadhikari approved these changes

2021-09-16 09:34 UTC, merged