added new version vehicle_positions
CanalTP/forseti pull request #67
Opened 2021-09-27 07:45 UTC by julyto

I created a new version for the position. I changed the name of the API to "vehicle_positions"
I will delete the old one after validation.

2021-09-27 10:00 UTC, kadhikari requested changes

2021-09-28 14:32 UTC, julyto commented on cmd/forseti/main.go
>  	// With vehicle locations
Changes are made in the main

2021-09-28 14:38 UTC, julyto commented on api/api.go
> +	VehiclePositions    LoadingStatus `json:"vehicle_locations,omitempty"`
Yes I changed

2021-09-28 14:38 UTC, julyto commented on cmd/forseti/main.go
Yes

2021-09-29 08:06 UTC, azime commented on internal/vehiclepositions/prometheus.go
> +		Subsystem: "vehicle_locations",
```suggestion
		Subsystem: "vehicle_positions",
```
No ?

2021-09-29 08:06 UTC, azime commented on internal/vehiclepositions/prometheus.go
> +		Subsystem: "vehicle_locations",
```suggestion
		Subsystem: "vehicle_positions",
```

2021-09-29 08:06 UTC, azime commented on internal/vehiclepositions/vehiclepositions_test.go
> +	date, err := time.ParseInLocation("2006-01-02", "2021-02-22", location)
Datetime, no ?

2021-09-29 08:56 UTC, julyto commented on internal/vehiclepositions/prometheus.go
> +		Subsystem: "vehicle_locations",
:+1:

2021-09-29 08:56 UTC, julyto commented on internal/vehiclepositions/prometheus.go
> +		Subsystem: "vehicle_locations",
:+1:

2021-09-29 08:58 UTC, julyto commented on internal/vehiclepositions/vehiclepositions_test.go
> +	date, err := time.ParseInLocation("2006-01-02", "2021-02-22", location)
As for Position, the API only uses a date "20060102"

2021-09-29 12:53 UTC, azime approved these changes

2021-09-29 12:59 UTC, julyto commented on internal/vehiclepositions/vehiclepositions.go
> +	}
:+1:

2021-09-29 18:45 UTC, benoit-bst approved these changes

2021-09-30 11:56 UTC, kadhikari approved these changes

2021-09-30 12:28 UTC, merged